import AppKit
import Foundation

/// Decides what never gets captured, and what gets captured but never written down.
///
/// Every clipboard manager has this logic; almost none of them show it to you. The
/// design bet here is that making it *visible* — a locked row that says
/// "Password · forgets in 58s" — is worth more than a checkbox in a settings
/// pane, because it turns an invisible promise into something you can check.
public enum PrivacyFilter {

    /// The nspasteboard.org marker for sensitive content: captured as a
    /// concealed clipping, whose text lives in memory until it expires.
    public static let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
    ]

    /// The nspasteboard.org markers for content not meant for history at all —
    /// an app's own intermediate copy, or something generated rather than
    /// chosen. Not recorded, not shown.
    public static let skippedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// Seeded on first launch so the safe default does not depend on anyone opening
    /// the settings screen. Users can remove entries; nothing here is enforced.
    public static let defaultIgnoredBundleIDs: Set<String> = [
        "com.agilebits.onepassword",
        "com.agilebits.onepassword7",
        "com.1password.1password",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.lastpass.LastPass",
        "com.dashlane.Dashlane",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "in.sinew.Enpass-Desktop",
    ]

    public enum Decision: Equatable, Sendable {
        case capture
        case conceal(reason: String)
        case ignore
    }

    public static func decide(
        types: [NSPasteboard.PasteboardType],
        sourceBundleID: String?,
        sourceAppName: String?,
        text: String?,
        ignoredBundleIDs: Set<String>
    ) -> Decision {
        if let sourceBundleID, ignoredBundleIDs.contains(sourceBundleID) {
            return .ignore
        }
        let available = Set(types)
        if skippedTypes.contains(where: available.contains) {
            return .ignore
        }
        if concealedTypes.contains(where: available.contains) {
            return .conceal(reason: sourceAppName ?? "a password manager")
        }
        if let text, looksLikeSecret(text) {
            return .conceal(reason: "looks like a credential")
        }
        return .capture
    }

    public static func decide(
        pasteboard: NSPasteboard,
        sourceBundleID: String?,
        sourceAppName: String?,
        text: String?,
        ignoredBundleIDs: Set<String>
    ) -> Decision {
        decide(types: pasteboard.types ?? [], sourceBundleID: sourceBundleID, sourceAppName: sourceAppName,
               text: text, ignoredBundleIDs: ignoredBundleIDs)
    }

    /// Prefix-matching on well-known credential formats. Cheap, high-precision, and
    /// on purpose *not* an entropy heuristic — flagging every base64 blob as a
    /// secret would conceal half of a developer's real clipboard history.
    public static func looksLikeSecret(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        // Real credentials are single tokens or PEM blocks, not paragraphs.
        guard trimmed.count >= 16, trimmed.count <= 4_096 else { return false }

        if trimmed.contains("-----BEGIN") && trimmed.contains("PRIVATE KEY") { return true }

        guard !trimmed.contains(" "), !trimmed.contains("\n") else { return false }

        let prefixes = [
            "ghp_", "gho_", "ghu_", "ghs_", "ghr_", "github_pat_",
            "sk-", "sk_live_", "sk_test_", "pk_live_", "rk_live_",
            "xoxb-", "xoxp-", "xoxa-", "xapp-",
            "AKIA", "ASIA",
            "AIza",
            "glpat-", "npm_", "dop_v1_", "shpat_",
        ]
        for prefix in prefixes where trimmed.hasPrefix(prefix) { return true }

        // JWTs: three base64url segments, and long enough to be carrying a payload.
        if trimmed.hasPrefix("eyJ") {
            let segments = trimmed.split(separator: ".")
            if segments.count == 3, trimmed.count > 60 { return true }
        }
        return false
    }
}
