import AppKit
import XCTest
@testable import CpKit

/// Capture end to end on a private, named pasteboard: write as another app
/// would, let the monitor poll, and look at what reached the store.
@MainActor
final class MonitorTests: XCTestCase {

    private var pasteboard: NSPasteboard!
    private var directory: URL!
    private var settings: Settings!
    private var archive: ClippingArchive!
    private var store: ClippingStore!
    private var monitor: PasteboardMonitor!
    private var captures = 0

    override func setUp() async throws {
        try await super.setUp()
        pasteboard = NSPasteboard(name: NSPasteboard.Name("dev.cp.tests.\(UUID().uuidString)"))
        directory = TestDirectory.make(name)
        settings = Settings(defaults: MemoryDefaults())
        settings.recognizeText = false
        archive = try ClippingArchive(directory: directory)
        store = ClippingStore(archive: archive, settings: settings, recognizer: nil)
        monitor = PasteboardMonitor(pasteboard: pasteboard, settings: settings, archive: archive)
        monitor.onCapture = { [unowned self] clipping, secret in
            self.captures += 1
            self.store.ingest(clipping, secret: secret)
        }
        monitor.start(interval: 0.02)
    }

    override func tearDown() async throws {
        monitor.stop()
        pasteboard.releaseGlobally()
        TestDirectory.remove(directory)
        try await super.tearDown()
    }

    /// Writes as another app would, then waits for the capture to land.
    @discardableResult
    private func copy(_ write: (NSPasteboard) -> Void) -> Bool {
        let expected = captures + 1
        pasteboard.clearContents()
        write(pasteboard)
        return waitUntil(timeout: 5) { self.captures >= expected }
    }

    private func settle() {
        RunLoop.main.run(until: Date().addingTimeInterval(0.2))
    }

    // MARK: - Own writes

    /// A paste from cp must never move, re-count or re-attribute a clipping.
    func testOwnWritesAreNeverCaptured() throws {
        XCTAssertTrue(copy { $0.setString("first", forType: .string) })
        XCTAssertTrue(copy { $0.setString("second", forType: .string) })
        let first = try XCTUnwrap(store.clippings.last)
        XCTAssertEqual(store.clippings.map(\.payload), ["second", "first"])

        let paster = Paster(pasteboard: pasteboard)
        monitor.ignore(changeCount: paster.write(PastePayload(string: first.payload)))
        settle()
        // Marked but not announced, as when a paste is swapped for another format.
        paster.write(PastePayload(string: "first"))
        settle()

        XCTAssertEqual(captures, 2)
        XCTAssertEqual(store.clippings.map(\.payload), ["second", "first"])
        XCTAssertEqual(store.clipping(withID: first.id)?.copyCount, 1)

        // The user copying the same text again is a real re-copy.
        XCTAssertTrue(copy { $0.setString("first", forType: .string) })
        XCTAssertEqual(store.clippings.map(\.payload), ["first", "second"])
        XCTAssertEqual(store.clippings.first?.copyCount, 2)
    }

    // MARK: - Privacy

    /// Transient and AutoGenerated mean "do not record"; only Concealed
    /// (and credential-shaped text) becomes a concealed clipping.
    func testPrivacyMarkers() throws {
        let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let generated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

        for marker in [transient, generated] {
            pasteboard.clearContents()
            pasteboard.declareTypes([.string, marker], owner: nil)
            pasteboard.setString("skip me", forType: .string)
            pasteboard.setString("", forType: marker)
            settle()
        }
        XCTAssertEqual(captures, 0)
        XCTAssertTrue(store.clippings.isEmpty)

        XCTAssertTrue(copy {
            $0.declareTypes([.string, concealed], owner: nil)
            $0.setString("hunter2-hunter2", forType: .string)
            $0.setString("", forType: concealed)
        })
        XCTAssertTrue(copy { $0.setString(FakeSecret.github, forType: .string) })

        XCTAssertEqual(store.clippings.count, 2, "two rows, one per copy")
        XCTAssertTrue(store.clippings.allSatisfy { $0.isConcealed && $0.payload.isEmpty })
        XCTAssertEqual(store.clippings.map { store.secret(for: $0.id) }, [FakeSecret.github, "hunter2-hunter2"])
        XCTAssertEqual(store.clippings.first?.detail, "looks like a credential")

        archive.flush()
        let log = (try? String(contentsOf: directory.appendingPathComponent("history.jsonl"), encoding: .utf8)) ?? ""
        XCTAssertFalse(log.contains("hunter2") || log.contains(FakeSecret.github))
    }

    // MARK: - Images

    private func screenshot(width: Int, height: Int, pointScale: CGFloat, color: NSColor) -> NSBitmapImageRep {
        let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: width, pixelsHigh: height, bitsPerSample: 8,
                                   samplesPerPixel: 4, hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB,
                                   bytesPerRow: 0, bitsPerPixel: 0)!
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
        color.setFill()
        NSRect(x: 0, y: 0, width: width, height: height).fill()
        NSGraphicsContext.restoreGraphicsState()
        rep.size = NSSize(width: CGFloat(width) / pointScale, height: CGFloat(height) / pointScale)
        return rep
    }

    /// Fixes 2, 13 and 18: images are hashed and measured off the main thread,
    /// in pixels, and dedupe on their bytes without leaving files behind.
    func testImagesCaptureInPixelsAndDedupeOnTheirBytes() throws {
        let red = try XCTUnwrap(screenshot(width: 400, height: 200, pointScale: 2, color: .systemRed).representation(using: .png, properties: [:]))
        let blue = try XCTUnwrap(screenshot(width: 400, height: 200, pointScale: 2, color: .systemBlue).representation(using: .png, properties: [:]))

        XCTAssertTrue(copy { $0.setData(red, forType: .png) })
        let first = try XCTUnwrap(store.clippings.first)
        XCTAssertEqual(first.kind, .image)
        XCTAssertEqual(first.pixelWidth, 400, "pixels, not the 200-point width")
        XCTAssertEqual(first.pixelHeight, 200)
        XCTAssertEqual(first.contentHash?.count, 32)
        XCTAssertEqual(first.title, "Image")
        XCTAssertEqual(first.payload, "Image 400×200")

        XCTAssertTrue(copy { $0.setData(blue, forType: .png) })
        XCTAssertEqual(store.clippings.filter { $0.kind == .image }.count, 2, "same size, different pictures")

        XCTAssertTrue(copy { $0.setData(red, forType: .png) })
        XCTAssertEqual(store.clippings.filter { $0.kind == .image }.count, 2)
        XCTAssertEqual(store.clippings.first?.id, first.id)
        XCTAssertEqual(store.clippings.first?.copyCount, 2)

        archive.flush()
        let onDisk = Set(try FileManager.default.contentsOfDirectory(atPath: archive.assetsDirectory.path))
        XCTAssertEqual(onDisk, Set(store.clippings.compactMap(\.assetFilename)), "no orphaned PNGs")
    }

    /// Converting and hashing a big TIFF used to happen inside the
    /// poll, on the main thread. Now the poll only reads bytes and returns; the
    /// capture arrives afterwards.
    func testImageWorkHappensAfterThePollReturns() throws {
        monitor.stop()
        let rep = screenshot(width: 3_000, height: 2_000, pointScale: 2, color: .systemTeal)
        let tiff = try XCTUnwrap(rep.tiffRepresentation)
        pasteboard.clearContents()
        pasteboard.setData(tiff, forType: .tiff)

        monitor.poll()
        XCTAssertEqual(captures, 0, "the poll returned before the image was converted")
        XCTAssertTrue(store.clippings.isEmpty)

        XCTAssertTrue(waitUntil(timeout: 10) { self.captures == 1 })
        XCTAssertEqual(store.clippings.first?.pixelWidth, 3_000)
        XCTAssertEqual(store.clippings.first?.pixelHeight, 2_000)
    }

    func testTIFFBecomesPNG() throws {
        let tiff = try XCTUnwrap(screenshot(width: 64, height: 32, pointScale: 1, color: .systemGreen).tiffRepresentation)
        XCTAssertTrue(copy { $0.setData(tiff, forType: .tiff) })
        let image = try XCTUnwrap(store.clippings.first)
        XCTAssertEqual(image.pixelWidth, 64)
        let file = try XCTUnwrap(image.assetFilename)
        let data = try Data(contentsOf: archive.assetURL(for: file))
        XCTAssertEqual(Array(data.prefix(4)), [0x89, 0x50, 0x4E, 0x47], "stored as PNG")
    }

    /// Numbers and Excel put a picture of the cells beside the cells.
    func testDocumentContentWithAnImageIsCapturedAsText() throws {
        let tiff = try XCTUnwrap(screenshot(width: 64, height: 32, pointScale: 1, color: .white).tiffRepresentation)
        let rtf = try NSAttributedString(string: "Q3\t48.20").data(
            from: NSRange(location: 0, length: 8), documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf])
        XCTAssertTrue(copy {
            $0.declareTypes([.rtf, .string, .tiff], owner: nil)
            $0.setData(rtf, forType: .rtf)
            $0.setString("Q3\t48.20", forType: .string)
            $0.setData(tiff, forType: .tiff)
        })
        XCTAssertEqual(store.clippings.first?.kind, .text)
        XCTAssertEqual(store.clippings.first?.payload, "Q3\t48.20")
    }

    // MARK: - Text

    /// Plain RTF is text; real formatting is rich, and its RTF is kept.
    func testRichTextOnlyWhenTheFormattingIsReal() throws {
        let words = "Just words, no styling at all"
        let plainRTF = try NSAttributedString(string: words).data(
            from: NSRange(location: 0, length: (words as NSString).length),
            documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf])
        XCTAssertTrue(copy {
            $0.declareTypes([.rtf, .string], owner: nil)
            $0.setData(plainRTF, forType: .rtf)
            $0.setString(words, forType: .string)
        })
        XCTAssertEqual(store.clippings.first?.kind, .text)
        XCTAssertEqual(store.clippings.first?.origin, .richText)
        XCTAssertNil(store.clippings.first?.richAssetFilename)

        let styled = NSMutableAttributedString(string: "Bold claim and a link")
        styled.addAttribute(.font, value: NSFont.boldSystemFont(ofSize: 13), range: NSRange(location: 0, length: 4))
        let rtf = try styled.data(from: NSRange(location: 0, length: styled.length),
                                  documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf])
        XCTAssertTrue(copy {
            $0.declareTypes([.rtf, .string], owner: nil)
            $0.setData(rtf, forType: .rtf)
            $0.setString(styled.string, forType: .string)
        })
        let rich = try XCTUnwrap(store.clippings.first)
        XCTAssertEqual(rich.kind, .richText)
        let file = try XCTUnwrap(rich.richAssetFilename)
        XCTAssertEqual(try Data(contentsOf: archive.assetURL(for: file)), rtf)
    }

    func testSourceURLAndFileURLs() throws {
        XCTAssertTrue(copy {
            $0.declareTypes([.string, NSPasteboard.PasteboardType("org.chromium.source-url")], owner: nil)
            $0.setString("a passage from a page", forType: .string)
            $0.setString("https://developer.apple.com/documentation/swiftui", forType: NSPasteboard.PasteboardType("org.chromium.source-url"))
        })
        XCTAssertEqual(store.clippings.first?.sourceURL, "https://developer.apple.com/documentation/swiftui")

        let urls = [URL(fileURLWithPath: "/Users/me/a.txt"), URL(fileURLWithPath: "/Users/me/b.png")]
        XCTAssertTrue(copy { $0.writeObjects(urls as [NSURL]) })
        let files = try XCTUnwrap(store.clippings.first)
        XCTAssertEqual(files.kind, .file)
        XCTAssertEqual(files.origin, .fileURLs)
        XCTAssertEqual(files.detail, "2 files")
        XCTAssertEqual(files.payload, "/Users/me/a.txt\n/Users/me/b.png")
    }

    func testPauseAndResume() {
        monitor.pause(for: nil)
        XCTAssertEqual(monitor.pausedUntil, .distantFuture)
        pasteboard.clearContents()
        pasteboard.setString("while paused", forType: .string)
        settle()
        XCTAssertEqual(captures, 0)

        monitor.resume()
        XCTAssertTrue(copy { $0.setString("after resuming", forType: .string) })
        XCTAssertEqual(store.clippings.map(\.payload), ["after resuming"])

        monitor.pause(for: 0.1)
        XCTAssertTrue(waitUntil { self.monitor.pausedUntil == nil }, "a timed pause ends by itself")
    }
}
