import AppKit
import XCTest
@testable import CpKit

final class PrivacyFilterTests: XCTestCase {

    func testDetectsKnownTokenPrefixes() {
        XCTAssertTrue(PrivacyFilter.looksLikeSecret(FakeSecret.github))
        XCTAssertTrue(PrivacyFilter.looksLikeSecret(FakeSecret.openAI))
        XCTAssertTrue(PrivacyFilter.looksLikeSecret(FakeSecret.slack))
        XCTAssertTrue(PrivacyFilter.looksLikeSecret(FakeSecret.aws))
        XCTAssertTrue(PrivacyFilter.looksLikeSecret(FakeSecret.gitLab))
    }

    func testDetectsPrivateKeyBlocks() {
        let pem = "-----BEGIN OPENSSH PRIVATE KEY-----\nabc\n-----END OPENSSH PRIVATE KEY-----"
        XCTAssertTrue(PrivacyFilter.looksLikeSecret(pem))
    }

    func testDetectsJWTs() {
        let jwt = FakeSecret.jwt
        XCTAssertTrue(PrivacyFilter.looksLikeSecret(jwt))
    }

    /// The precision half of the bargain. Flagging every base64-ish string would
    /// conceal a large slice of a developer's real history, which is worse than
    /// missing the occasional bespoke token format.
    func testDoesNotFlagOrdinaryContent() {
        XCTAssertFalse(PrivacyFilter.looksLikeSecret("hello world"))
        XCTAssertFalse(PrivacyFilter.looksLikeSecret("https://github.com/org/repo"))
        XCTAssertFalse(PrivacyFilter.looksLikeSecret("short"))
        XCTAssertFalse(PrivacyFilter.looksLikeSecret("a sentence with several words in it"))
        XCTAssertFalse(PrivacyFilter.looksLikeSecret("d3adb33fd3adb33fd3adb33fd3adb33f"))
    }

    /// Transient and AutoGenerated items are not recorded at all; only
    /// Concealed becomes a concealed clipping.
    func testMarkerTypesDecideBetweenSkippingAndConcealing() {
        func decide(_ types: [String], text: String? = "text") -> PrivacyFilter.Decision {
            PrivacyFilter.decide(types: types.map { NSPasteboard.PasteboardType($0) } + [.string],
                                 sourceBundleID: "com.example.app", sourceAppName: "Example", text: text,
                                 ignoredBundleIDs: [])
        }
        XCTAssertEqual(decide(["org.nspasteboard.TransientType"]), .ignore)
        XCTAssertEqual(decide(["org.nspasteboard.AutoGeneratedType"]), .ignore)
        XCTAssertEqual(decide(["org.nspasteboard.ConcealedType"]), .conceal(reason: "Example"))
        XCTAssertEqual(decide(["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType"]), .ignore)
        XCTAssertEqual(decide([], text: FakeSecret.github), .conceal(reason: "looks like a credential"))
        XCTAssertEqual(decide([]), .capture)
        XCTAssertEqual(PrivacyFilter.decide(types: [.string], sourceBundleID: "com.bitwarden.desktop", sourceAppName: nil,
                                            text: "x", ignoredBundleIDs: PrivacyFilter.defaultIgnoredBundleIDs), .ignore)
    }

    func testPasswordManagersAreIgnoredByDefault() {
        XCTAssertTrue(PrivacyFilter.defaultIgnoredBundleIDs.contains("com.agilebits.onepassword"))
        XCTAssertTrue(PrivacyFilter.defaultIgnoredBundleIDs.contains("com.bitwarden.desktop"))
        XCTAssertTrue(PrivacyFilter.defaultIgnoredBundleIDs.contains("org.keepassxc.keepassxc"))
    }
}
